/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.entities.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEntitiesScopeProvider extends DelegatingScopeProvider {
}
