/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.entities.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.entities.EntitiesRuntimeModule;
import org.xtext.example.entities.EntitiesStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EntitiesIdeSetup extends EntitiesStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EntitiesRuntimeModule(), new EntitiesIdeModule()));
	}
	
}
