/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.entities.ide;


/**
 * Use this class to register ide components.
 */
public class EntitiesIdeModule extends AbstractEntitiesIdeModule {
}
