/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.entities.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EntitiesUiModule extends AbstractEntitiesUiModule {

	public EntitiesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
